### ISSUE TITLE
Unknown App Engine Region Code: europe-west2-a

### ISSUE THREAD

**Issue by paumas** [a1comms/GaeFlexSupportL5#57]
I used Google App Engine Flexible Environment and I get error:
```
PHP Notice: Exception: Unknown App Engine Region Code: europe-west2-a in 
/app/vendor/a1comms/gae-support-laravel/src/A1comms/GaeSupportLaravel/Integration/TaskQueue/Client.php:61
```

**Comment by matthewnessworthy** [comment]
@paumas sorry for the delayed response, i didn't see this issue 

can you log the value of `$zone` before the switch statement and report back the value please?
alternatively, you can also find the zone in the `resource` section of the access log entry in Stackdriver Logging

**Comment by paumas** [comment]
My zone is europe-west2-a.
You can see all zones: https://cloud.google.com/compute/docs/regions-zones

**Comment by matthewnessworthy** [comment]
please see https://github.com/matthewnessworthy/GaeSupportLaravel/blob/php72-laravel55/src/A1comms/GaeSupportLaravel/Integration/TaskQueue/Client.php#L51 for the current mapping

**Comment by paumas** [comment]
I forked this repository and fixed.
https://github.com/paumas/GaeSupportLaravel/blob/5b306f1d110c5e1ff752fe15bbe6d41fda23d4fc/src/A1comms/GaeSupportLaravel/Integration/TaskQueue/Client.php#L60

**Comment by matthewnessworthy** [comment]
I'm not sure if your task queue will actually work with that, or if that's just obscuring the instantiation error.

**Comment by paumas** [comment]
I tried and it works for me.

**Comment by iamacarpet** [comment]
Hi all,

I thought we'd already pushed a fix for this, but apprently not as I can't see it anywhere, sorry!

Basically, to remain compatible with Standard and Flexible environments and make it easy for everyone, we should probably do this:

* Detect if the zone is in the format "europe-west1-a", i.e. has 3 parts if split on "-": if so, strip the last part (e.g. "-a") and pass it through as-is.
* Otherwise fallback to the manual mapping for when it uses a non-standard region / zone, like on App Engine Standard Env.

@matthewnessworthy , would you mind assisting with this please? It'll be a couple of weeks until I'll be able to get to it otherwise.

Regards,
iamacarpet

**Comment by iamacarpet** [comment]
By the way, @mtraver , any news on if we'll be able to pull the region from the metadata server any time soon, to save all the pain with this manual mapping?

On the Standard Environment I mean (slightly unrelated to this ticket), as it still returns App Engine specific region codes, like "eu6", "us10", etc.
