### ISSUE TITLE
Batch Daemon on the Standard Environment (GAE)

### ISSUE THREAD

**Issue by iamacarpet** [a1comms/GaeFlexSupportL5#72]
It would be great to have the batch daemon on the Standard Environment, as not only would it support better async submission of both logs & trace entries, it would also allow us to use Stackdriver Debugger with live breakpoints/logpoints, etc.

So far, we tested it on Flex but we've struggled to enable it on the Standard Environment.

**Comment by iamacarpet** [comment]
Our new team member, @Miscreancy , helped us with a method of starting a background daemon reliably with a custom bash entry point, so we finally managed to give this a try properly.

However, the batch daemon won't start, as the SystemV IPC functionality isn't present in the PHP runtime on the Standard Environment.

Unfortunately, according to the PHP docs, it has to be compiled as part of PHP itself, it can't be added later as a PECL module:

https://www.php.net/manual/en/sem.installation.php

I have asked the App Engine PM if it'll be possible to get this included in the runtime, but since we asked during the alpha for php72 and it never made the cut, it is probably doubtful they'll be able to add it now.

On another note, since we last looked, Cloud Debugger has been separated into it's own daemon which doesn't seem to depend on the semaphore stuff, so we managed to give this a try.

We used a custom entrypoint script:
https://github.com/a1comms/GaeSupportLaravel/blob/1fa6fb5b4ee7eb8a319ab8424c03ad6723dc3ddd/src/scripts/entrypoint_debugger.sh

Plus some changes to the `preload.php` script that sets up the initial environment:
https://github.com/a1comms/GaeSupportLaravel/blob/1fa6fb5b4ee7eb8a319ab8424c03ad6723dc3ddd/src/preload.php#L28

I managed to test the "snapshot" functionality, to request & capture a stack trace, which did /usually/ work, although not very reliably during my testing.

The functionality we were more interested in, "logpoints", didn't seem to work at all.

You'll notice in the changes to `preload.php`, we are passing in a custom logger, as by default it uses one that excepts the batch daemon to be present, however, even with this custom logger loaded, none of the log points seem to run: it's as if they just aren't injected into the code as they should be.

Overall, while the functionality of Stackdriver Debugger sounds amazing on the face of it, if it's unreliable and/or doesn't really work, it'll probably cause more trouble that it's worth, so for now at-least, we'll choose to leave it off.

I'll leave this ticket open as a placeholder for the fact that we'd still like to see the batch daemon for async Trace submission.

**Comment by flexgrip** [comment]
I ended up mangling a script together that would serve me one of these failed-items files. After all that, I opened it up and it is encoded with something. Unreadable hex looking stuff.

So I'm back to square one. Going to try forking the gcloud package and overriding that function so that it just doesn't write those files. I just wish I could determine what it is writing into those files. I don't know if they are necessary or not.

**Comment by flexgrip** [comment]
Although I still don't know what was in those failed-items files, I did manage to fork and alter the `HandleFailedItemsTrait` that was writing those files. Instead of writing those files I just had it return true.

I had to wrestle with duplicate copies of CloudTrace and things like that in composer, but I'm happy to report that once I got it working it seems to have fixed the memory leak issue. It is a wonderful feeling to have gae standard env running efficiently again. And to be reliable/trustworthy. I love app engine ;)

To summarize:
1. Whatever google/core/batch is doing, it was writing a bunch of data to /tmp as "failed-items" files.
2. I wrote a little script to show me the listing for the /tmp directory, along with the file sizes of all of the files in there. Noticed that those failed-items files grow and grow. At one point I saw that they were ~300mb when you combine them all.
3. For those that don't know, the /tmp directory is basically the only writable part of the file system in gae standard envs. The reason it's writable is because it's basically just a tmpfs mount or "ram disk".
4. When those files consumed too much memory, other more demanding requests would cause the instance to kill itself and report that it had exceeded its memory usage.
5. Disabling the ability for `HandleFailedItemsTrait` in google/core/batch/ to write those failed-items files solved the problem.
6. This was tested in one of our small micro services. Vanilla crud service on laravel + a1comms package. Same result. Filling up ram until it kills the instance and randomly shows users a 500.

I'm unsure if the a1comms package has anything to do with it, other than its usage of google/cloud-core. But in order to do a post-mortem on this, I would need to really understand what the batch runner is doing and what it is putting in those failed-items files. **My current theory** is that in the every day job of laravel, it is trying to log something. Maybe events are firing off log entries with high frequency and there's something broken or not configured right with the google batch library. So instead of writing something to stackdriver (or somewhere) it is just flooding those failed-items files.

I have no evidence to support my theory. Just a gut feeling.

Thank you all for your help with all of this. I realize that you don't have to help with any of this work and it's solely out of the goodness in your heart that you even engaged this ticket. I wish I could be more helpful and repay the favor. Maybe some PR's down to road (we want to abstract more functionality in the future from this package and use it independently).
